import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
<<<<<<< HEAD
import ApolloClientProvider from "@/providers/ApolloClientProvider";
import { Toaster } from "react-hot-toast";      
=======
import { ThemeProvider } from "./ThemeProvider";
>>>>>>> 378d3d01ef40fbc431a9b5e2521ce6ba54ecff7e
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/3.0.0/modern-normalize.min.css"
          integrity="sha512-3axTZ/bKFZH5/qLFTl4U+mDbBDFW+5QO5L7D1HnOhlhJbcNDIVJxoNm6It77g0eUdzfKZlHirayqRC2qJaAOJw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <body className={inter.className}>
<<<<<<< HEAD
        <ApolloClientProvider>{children}
          <Toaster />
        </ApolloClientProvider>
=======
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
>>>>>>> 378d3d01ef40fbc431a9b5e2521ce6ba54ecff7e
      </body>
    </html>
  );
}
